obj-$(CONFIG_MSM_MDSS_PLL) += mdss-pll-util.o
obj-$(CONFIG_MSM_MDSS_PLL) += mdss-pll.o
obj-$(CONFIG_MSM_MDSS_PLL) += mdss-dsi-pll-util.o
obj-$(CONFIG_MSM_MDSS_PLL) += mdss-dsi-pll-28lpm.o

# MSM8996
ifeq ($(CONFIG_ARCH_MSM8996), y)
  obj-$(CONFIG_MSM_MDSS_PLL) += mdss-dsi-pll-8996.o
  obj-$(CONFIG_MSM_MDSS_PLL) += mdss-dsi-pll-8996-util.o
  obj-$(CONFIG_MSM_MDSS_PLL) += mdss-hdmi-pll-8996.o
endif
